### ISSUE TITLE
Middleman + Livereload + Pow

### ISSUE THREAD

**Issue by kierzniak** [middleman/middleman-livereload#14]
I have problem to use middleman-livereload with pow. After insert this line to config.rb

```
activate :livereload, :host => "project.dev"
```

Pow is displaying error 

```
Error starting application
Your Rack app raised an exception when Pow tried to run it.
Error: Response was not received
Error: Response was not received
    at Client._finishRequest (/Users/kierzniak/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/client.js:77:27)
    at Client.<anonymous> (/Users/kierzniak/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/client.js:38:21)
    at Client.emit (events.js:88:20)
    at Array.0 (net.js:335:10)
    at EventEmitter._tickCallback (node.js:190:38)
```

I assume that middleman-livereload is adapted to middleman server but if there is any chance to use it with pow?

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

*(this repo is maintained by a few people contributing their free time, unfortunately we can't solve every issue on our own, so help from others is needed for some of the more exotic issues that crops up)*

**Comment by indirect** [comment]
I'm using [puma-dev](https://github.com/puma/puma-dev) instead of pow, but I ran across this issue while trying to get livereload working, and it provided enough hints I was able to get it working after some debugging. Good luck, future troubleshooters.

```
# config.rb (lines added only)
activate :livereload, host: "0.0.0.0", port: 35730
```

```
# config.ru
require 'bundler/setup'
require 'middleman/rack'
require 'rack/livereload'

use Rack::LiveReload, port: 35730, no_swf: true
run Middleman.server
```
