### ISSUE TITLE
Ignore directory

### ISSUE THREAD

**Issue by LimeBlast** [middleman/middleman-livereload#24]
Hi, I'm not sure if this is a problem, or if it's something I can just let slide, but livereload is causing the page to reload when files in my IDE's project folder are updated, i.e.

```
== The Middleman is standing watch at http://0.0.0.0:4567
== LiveReloading path: index.html
== LiveReloading path: /srv/www/middleman.tld/.idea/workspace.xml
```

How can I get livereload to ignore the `.idea` folder?

My current config.ru file has this line:

```
activate :livereload, :host => '192.168.0.100'
```

I've tried adding `:ignore => *****` to the end of it, but I don't know the correct syntax to use.

Cheeers.

**Comment by shaekuronen** [comment]
Has this syntax been updated? In the readme, an ignore option is listed without an example.  I tried
```
# Reload the browser automatically whenever files change
configure :development do
  activate :livereload, ignore: [
    'bower_components/*',
    'node_modules/*',
    'images/*'
  ]
end
```
which seems pretty standard config.rb config but get this error
```
.rvm/gems/ruby-2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/configuration.rb:158:in `define_setting': Setting ignore doesn't exist (RuntimeError)
```
this seems to be working, but is it the recommended syntax?
```
configure :development do
  activate :livereload
  config[:file_watcher_ignore] += [
    /bower_components\//,
    /node_modules\//,
    /images\//
    ]
end
```

**Comment by tdreyno** [comment]
@shaekuronen The `ignore` option was just added very recently and hasn't been pushed out to Rubygems. The version on github master should have it.

**Comment by Dovizu** [comment]
Still can't use that option, even though it is documented. When will the code be pushed out to ruby gems?

**Comment by tdreyno** [comment]
Just released `v3.4.3`

**Comment by Dovizu** [comment]
Works great/ Thanks!

**Comment by nikisakovich** [comment]
What is the correct syntax for the latest `v3.4.3`?
I tried adding `ignore: ['.idea/*']`, `ignore: [/.idea\//]`, `:ignore => ['.idea/*']` after `activate :livereload, `, but still livereload watched that folder.
However, adding `config[:file_watcher_ignore] += [/.idea\//]` worked.

**Comment by tdreyno** [comment]
`ignore: [/.idea\//]` should work

**Comment by nikisakovich** [comment]
I tried one more time and still got false reloads.
I'm on Windows 7, Ruby 2.2.2, Middleman 3.4.0, middleman-livereload 3.4.3 (from RubyGems).
This is written in `config.rb`:
```
configure :development do
  activate :livereload, ignore: [/.idea\//]
end
```
When I edit `index.html.erb` and switch to browser I see this in RubyMine console:
```
== LiveReloading path: /
== LiveReloading path: D:/project/.idea/workspace.xml
```
So seems like this option isn't working for me. Not a big problem though, config thing helps :)

**Comment by tdreyno** [comment]
We're just proxying to the `rack-livereload` gem, not sure where the bug is
