### ISSUE TITLE
Using it on a remote server

### ISSUE THREAD

**Issue by LimeBlast** [middleman/middleman-livereload#26]
I can't tell if this is something that I'm doing wrong, or if it's a bug with middleman or livereload, but I'm unable to get it to work correctly on my remote server set-up.

I've got a Debian machine (called `green`) which I use for all my development. Seeing as middleman comes with its own development server built in, I've been running that and have been able to successfully connect to via: http://green:4567/

So far so good

The issues start when I try to enable livereload, which I do by adding `activate :livereload` to my `config.rb` file. So far as I can tell, livereload is working as intended as I get the starting message:

```
== LiveReload is waiting for a browser to connect
```

But when connecting to the site using the link above, my livereload addon automatically enables itself, but I started to get a bunch of aborted connections to http://0.0.0.0:35729/livereload showing in firebug.

I've tried to edit the `config.rb` file to include the name and ip of the server (i.e. `activate :livereload, :host => 'green'`), but this hasn't worked, nor has my trick of getting livereload to work with [Guard](https://github.com/guard/guard), which is to set-up a local tunnel to the remove server for port 35729.

All in all, I'm a bit lost as to how to solve this problem - can someone point me in the right direction? Thank you.

**Comment by veryangrymobster** [comment]
Firefox wasn't refreshing when the source file change. Using 
`activate :livereload, :host => '127.0.0.1'`
fixed the problem.
