### ISSUE TITLE
Preventing full webpage reload (just reload CSS) with LiveReload in Compass projects

### ISSUE THREAD

**Issue by tdreyno** [middleman/middleman-livereload#3]
Originated in:
https://github.com/tdreyno/middleman/issues/105

**Comment by javaporter** [comment]
Has anyone figured out a work-around for this? I saw the fork, but I'm not sure if that fixes it. 

My issue is this: I've been working on a few node projects, and livereload is instant. MM, in contrast, feels incredibly sluggish. Other than the pokey livereload, it's a brilliant tool and does everything I want. But that 1-2 second lag for every minor CSS change? Ugh. 

I usually have an app.scss file and then do imports from there. (Thanks for including sass globbing btw.)

```
@import 'normalize'
@import 'bourbon'
@import 'neat'

@import 'variables'

@import 'global/*'
@import 'components/*'
@import 'pages/*'
```

**Comment by tdreyno** [comment]
Nobody on the core team uses live reload, so that extension suffers very heavily. We'd love assistance from developers who actually use the tool.

**Comment by javaporter** [comment]
Thanks for the reply. What do you use? Is there a better option? Or do you just manually refresh?

**Comment by tdreyno** [comment]
I manually refresh... I am old school. I've heard good things about BrowserSync too. Would love some help making that support better.

**Comment by javaporter** [comment]
Yeah, browsersync is nice, it seems like everyone is headed in that direction. I tried that this afternoon. I tried using the github version of mm-livereload and ignoring the sass `activate :livereload, ignore: ['assets/stylesheets/*']`, then using browser sync, but it didn't seem to really be ignoring the sass (it still reloaded the page on saving sass files). If you turn off livereload altogether then browsersync works great (fast too), but then you have to manually reload your .slim (or haml or erb or whatever your flavor is). 

Seriously though, if this is my biggest complaint about MM (and it probably is), then well-done. I've tried the other static compilers (mostly the node-sass ones), but no one has everything MM has. It's the little things that you really start to take for granted.

**Comment by riddla** [comment]
The fork at https://github.com/wazeHQ/middleman-livereload/commit/711b87eeb5f58f957531404bb6b7673e04493f71 works for me.

It can be used as follows:

```
gem 'middleman-livereload', :git => 'https://github.com/wazeHQ/middleman-livereload', :branch => 'css_reload'
```

**Comment by javaporter** [comment]
Works like a charm @riddla, I'm trying it out now. Thanks much.

**Comment by tdreyno** [comment]
Would love a PR into core :)

**Comment by riddla** [comment]
@wazeHQ: Would you do a PR with your work?

**Comment by amirnissim** [comment]
@riddla @tdreyno happy to, see #77

**Comment by NathanBowers** [comment]
Does #77 really work? I'm using the #77 fork and still getting full page reload when I modify imported Sass files. Just saving application.css.sass works as expected though (just a socket reload of the generated css).

**Comment by NathanBowers** [comment]
@tdreyno I'd encourage you and the MM team to start using LiveReload, BrowserSync, etc. because your users definitely are.

(When developing for 12 different devices and god only knows how many browsers open, pressing refresh on all of them to see changes becomes unworkable real quick.)

:sparkling_heart: Middleman! 

https://twitter.com/colincornaby/status/664512996085927936/photo/1

**Comment by amirnissim** [comment]
@NathanBowers #77 is already merged in master. I have
```ruby
gem "middleman-livereload", github: 'middleman/middleman-livereload'
```
in my `Gemfile` and it works as expected:
Modifying a `.scss` file that is `@imported` in `application.css.scss` does not trigger full page refresh and `application.css` is reloaded.

Can you provide more details on your setup?

**Comment by NathanBowers** [comment]
I made a clean new Middleman project with `$middleman init` and I'm on Middleman 4.0.0 rc 2

Gemfile: 
```
# Middleman Gems
gem 'middleman', '>= 4.0.0.rc.2'
gem "middleman-livereload", github: 'middleman/middleman-livereload'
```

Then I added `_test.scss` in `/source/stylesheets/` with `@import "test";`  in `site.css.scss`

When I save `site.css.scss` the full page does not reload, just an in-place CSS reload, as desired.

When I save `_test.css.scss` the full page does reload. 

I made a Vine of it: https://vine.co/v/i75FPmrh0KK (The red reload is `site.css.scss`, the blue reload is `_test.scss`)

Also, this is what I see in Terminal when I save `_test.scss` (It Livereloads both files, but note the different paths): 
```
== LiveReloading path: /Users/Nathan/Sites/middlemansites/test/stylesheets/_test.scss
== LiveReloading path: /stylesheets/site.css
```

When I save `site.css.scss` only site.css Livereloads:
```
== LiveReloading path: /stylesheets/site.css
```

**Comment by tdreyno** [comment]
That output matches what I'd expect. Is there a bug?

The different path is because there is no "output path" known to MM for the partial, because it is not included in a build (other than through inclusion)

**Comment by amirnissim** [comment]
@NathanBowers  Did you set [`:bundle_file_css`](https://github.com/middleman/middleman-livereload#bundle_file_css)? By default it will try to reload `application.css` when detecting a partial changed, and in your case you should `set bundle_file_css: 'site.css'`

**Comment by amirnissim** [comment]
@NathanBowers indeed, there is a problem. Will have a fix soon hopefully :)

**Comment by NathanBowers** [comment]
@amirnissim 

I didn't set `:bundle_file_css`. I was aware that it defaults to`application.css`, but since `middleman init` creates `site.css.scss` by default and correctly LiveReloads `site.css.scss` I thought maybe you changed the default. 

In any case, I'm assuming based on your latest comment that you confirmed the bug and don't need any further clarification from me, but please reach out if you do anything from me.

:sparkling_heart: :sparkling_heart: :sparkling_heart: :sparkling_heart:

**Comment by amirnissim** [comment]
@NathanBowers I have a fixed version over at our [fork](https://github.com/wazeHQ/middleman-livereload/tree/css_reload). Tested with a new app available [here](https://github.com/amirnissim/mmapp) and everything seems to be working now.

Can you confirm it works for you as well? you should set
```ruby
#config.rb

configure :development do
  activate :livereload, livereload_css_target: 'stylesheets/site.css'
end
```

**Comment by NathanBowers** [comment]
I can confirm that your middleman-reload fork and your new testing app scss imported css Livereloads as expected. 

Only issue I see is that your fork doesn't work with _underscore prefixed imported files. Hyphenated files LiveReload correctly (both Sass and Scss). 

Underscored files still do a full page reload.

```
-partial.sass                 // THIS LIVERELOADS GREAT!
_underscored.partial          // This will still refresh whole page instead of Livereloading
```

**Comment by tdreyno** [comment]
Let me know when the fork is ready to PR into this project

**Comment by amirnissim** [comment]
@NathanBowers live reload is not triggered because your're filenames are missing a `.css` extension.
The default pattern is `_.*\.css` so you could either (1) rename your files or (2) set `livereload_css_pattern: Regexp.new('_.*\.sass')`

**Comment by amirnissim** [comment]
@tdreyno PR ready https://github.com/middleman/middleman-livereload/pull/83
updates guides as well https://github.com/middleman/middleman-guides/pull/544

**Comment by tdreyno** [comment]
Thanks!

**Comment by NathanBowers** [comment]
@amirnissim You're right, although `-partial.sass` Livereloads correctly, while `_part.sass` does a full page reload, meanwhile `_partial.css.scss` works correctly.

Problem is if you put the .css extension on files, like `-partial.css.sass`, partials will be exported as files on `middleman build`, which clutters the static build. Generally, partials should be underscored and without the output file type (.css, .html, etc.).
