### ISSUE TITLE
middleman-livereload with middlman-deploy

### ISSUE THREAD

**Issue by ghost** [middleman/middleman-livereload#41]
Can you have it so that livereload only runs on development rather than not working if it's during build?

https://codeclimate.com/github/middleman/middleman-livereload/Middleman::LiveReloadExtension

The problem is when we use the middleman-deploy function, livereload tries to run there as well, which doesn't make sense.
https://github.com/tvaughan/middleman-deploy/issues/51

**Comment by chrishough** [comment]
I used the following to get around this in case anyone needs a quick fix:
```ruby
if ENV["LIVERELOAD"]
  configure :development do
    activate :livereload, host: '127.0.0.1'
  end
end
```

**Comment by doodybrains** [comment]
any updates here? also issue with LiveReload and middleman deploy

**Comment by tdreyno** [comment]
The above is the recommended solution for v3. Should be fixed in v4 out of the box
