### ISSUE TITLE
CSS not being applied live for @import-ed files.

### ISSUE THREAD

**Issue by paulozoom** [middleman/middleman-livereload#51]
I’m on middleman (3.2.2) and middleman-livereload (3.2.1). Whenever I make a change on `all.css.scss`, the CSS is applied live. But if said change is made in a file that `all.css.scss` imports with the Sass `@import` directive, the whole page is reloaded.

I believe this wasn’t happening when I first started this Middleman project, but now it is. However, I can’t pinpoint the culprit. Any idea why is this happening?

**Update:** This still happens with middleman-livereload 3.3.0

**Comment by amirnissim** [comment]
@tdreyno is it possible to default to `application.css` reload whenever a `*.scss` file changes?
