### ISSUE TITLE
Livereload + lots of changes = bad times

### ISSUE THREAD

**Issue by Ross-Hunter** [middleman/middleman-livereload#68]
Not sure if this is a livereload issue or middleman-livereload issue, but I have not experienced this when using livereload in any other context.

When I make a bunch of changes, say, switching from one branch to another where I have moved a folder with 100+ files in it, livereload kicks off a page reload _per file_, which usually results in me having to launch activity monitor and kill ruby, otherwise it will reload 100+ times in a row. Terminating the middleman process via `ctrl + c` doesn't stop it.

I haven't seen anyone else complaining about it, so it's possible I'm just not configured properly.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

*(this repo is maintained by a few people contributing their free time, unfortunately we can't solve every issue on our own, so help from others is needed for some of the more exotic issues that crops up)*

**Comment by Ross-Hunter** [comment]
This doesn't appear to be a big issue for most people, and I no longer have this use-case anymore so I'm happy to prune this issue :)
