### ISSUE TITLE
Passing paths or urls?

### ISSUE THREAD

**Issue by LMolr** [middleman/middleman-livereload#72]
I am not familiar to livereload in general, but reading the code it seems that what is sent through the websocket is sometimes a file path, sometimes an url.
Since the reloading means refresh urls, i would think that the correct thing to pass is an url.
Am i wrong? Can anyone clarify on this (or give a pointer to readings)? Thank you.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

*(this repo is maintained by a few people contributing their free time, unfortunately we can't solve every issue on our own, so help from others is needed for some of the more exotic issues that crops up)*
