### ISSUE TITLE
Expose Rack::LiveReload's ignore option.

### ISSUE THREAD

**Issue by kevincox** [middleman/middleman-livereload#73]
Currently there is no way to select which files get the livereload script tag injected in them.  This causes problems when you are transmitting html fragments (such as for html imports) and rack tries to insert it's script tag and ends up turning it into a document.  If Rack::LiveReload's ignore option was exposed it would be easy to prevent these files from being modified.

**Comment by Arcovion** [comment]
Is this sufficient?
https://github.com/Arcovion/middleman-livereload/commit/9c72eb8297127a5a58c1bb143fb655a6238e26df

Try with:
`gem 'middleman-livereload', github: 'arcovion/middleman-livereload', branch: 'ignore-option'`

I've only done this change through github, no actual testing...

**Comment by kevincox** [comment]
I believe you also have to pass it to livereload [here](https://github.com/middleman/middleman-livereload/blob/238d4c069ef11ac7154a493026c66641abb13aa2/lib/middleman-livereload/extension_3_1.rb#L63).

**Comment by kevincox** [comment]
You are so fast I barely had time to implement my quick, ugly workaround but I'll post it here in case it is useful.

```ruby
	activate :livereload
	ready do
		self.class.instance_variable_get(:@middleware)[-1][1][0][:ignore] = [
			%r(^/assets/),
			# Other ignore paths.
		]
	end
```

Ensure that you add the block **right** after activating livereload.

**Comment by kevincox** [comment]
Thanks!  Works perfectly.
