### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by cbetta** [middleman/middleman-livereload#81]
Are there any tests?

**Comment by tdreyno** [comment]
Would love to figure out a way to do tests, but all this extension really does it emit events over websockets. It's up to the client side JS or extension to actually do anything.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while!

If you have thoughts on how to improve testing, I'll happily review a PR! For now I'm going to close this issue though.

*(this repo is maintained by a few people contributing their free time, unfortunately we can't solve every issue on our own, so help from others is needed for some of the more exotic issues that crops up)*
