### ISSUE TITLE
Livereload proxy page when data changes

### ISSUE THREAD

**Issue by lbischof** [middleman/middleman-livereload#86]
Currently livereload doesn't work when I change data.

**Comment by lbischof** [comment]
It seems livereload notices that the data files have changed, but the content is not updated. So I'll move this issue over to the middleman repo.

**Comment by lbischof** [comment]
Building or restarting the server works. It seems livereload doesn't refresh the correct files. If I edit the erb document then the site correctly refreshes and shows the updated data.

**Comment by tdreyno** [comment]
Which version? This is fixed on v4 IIRC

**Comment by lbischof** [comment]
Using the latest v4. The site correctly detects the change of the datafile and refreshes the page, but doesn't rebuild the erb that's behind the proxy url:
```
proxy proxy_page_var, "/page.html" ...
```
If I open/save page.html.erb again the livereload rebuilds the source files and reloads the page correctly.

**Comment by tdreyno** [comment]
I can see why this is happening with proxies in v4, but I don't have a solution right now.

**Comment by lbischof** [comment]
Is there any way I could manually (in config.rb) tell livereload which files are linked?

**Comment by jayliu50** [comment]
Same issue here. Would like to specify dependencies manually.

**Comment by komor72** [comment]
@tdreyno, this issue also seems to be resolved, if I correctly understand what was the problem. I use reloading of both proxy-template files (.haml) and proxy-data reloading (/data/*.yml) just fine in 4.x.x projects.
