### ISSUE TITLE
Websocket Doesn't Respond in Daemon Mode

### ISSUE THREAD

**Issue by little-apps** [middleman/middleman-livereload#98]
I'm using [Slate](https://github.com/lord/slate), which is used to generate documentation and utilizes middleman. I tried adding LiveReload (this repo) to it and I've run into an odd problem. If I run middleman interactively (in the foreground), it works no problem. But when I run middleman as a daemon (in the background), the Websocket doesn't work. More specifically, I can connect to the port but it doesn't respond (the "!!ver:1.6" string isn't sent). 

I did some further investigating and found the following:
 * I thought it might be related to the Slate so I just did an empty installation of middleman with LiveReload. The problem still occurred.
 * I disabled the firewall.
 * I've tried Firefox and Chrome.

# Info #

 * CentOS Linux 7 (Core)
 * Ruby 2.2.2p95 & 2.4.0p0

### Gemfile ###

    source 'https://rubygems.org'

    # Middleman
    gem 'middleman', '~>4.2.1'
    gem 'middleman-syntax', '~> 3.0.0'
    gem 'middleman-autoprefixer', '~> 2.7.0'
    gem "middleman-sprockets", "~> 4.1.0"
    gem 'rouge', '~> 2.0.5'
    gem 'redcarpet', '~> 3.4.0'
    gem 'mini_racer'
    gem 'middleman-livereload', "~> 3.4.3"

### Gemfile.lock ###

	GEM
	  remote: https://rubygems.org/
	  specs:
		activesupport (5.0.4)
		  concurrent-ruby (~> 1.0, >= 1.0.2)
		  i18n (~> 0.7)
		  minitest (~> 5.1)
		  tzinfo (~> 1.1)
		addressable (2.5.1)
		  public_suffix (~> 2.0, >= 2.0.2)
		autoprefixer-rails (6.7.7.2)
		  execjs
		backports (3.8.0)
		coffee-script (2.4.1)
		  coffee-script-source
		  execjs
		coffee-script-source (1.12.2)
		compass-import-once (1.0.5)
		  sass (>= 3.2, < 3.5)
		concurrent-ruby (1.0.5)
		contracts (0.13.0)
		dotenv (2.2.1)
		em-websocket (0.5.1)
		  eventmachine (>= 0.12.9)
		  http_parser.rb (~> 0.6.0)
		erubis (2.7.0)
		eventmachine (1.2.3)
		execjs (2.7.0)
		fast_blank (1.0.0)
		fastimage (2.1.0)
		ffi (1.9.18)
		haml (5.0.1)
		  temple (>= 0.8.0)
		  tilt
		hamster (3.0.0)
		  concurrent-ruby (~> 1.0)
		hashie (3.5.6)
		http_parser.rb (0.6.0)
		i18n (0.7.0)
		kramdown (1.14.0)
		libv8 (5.9.211.38.1)
		listen (3.0.8)
		  rb-fsevent (~> 0.9, >= 0.9.4)
		  rb-inotify (~> 0.9, >= 0.9.7)
		memoist (0.16.0)
		middleman (4.2.1)
		  coffee-script (~> 2.2)
		  compass-import-once (= 1.0.5)
		  haml (>= 4.0.5)
		  kramdown (~> 1.2)
		  middleman-cli (= 4.2.1)
		  middleman-core (= 4.2.1)
		  sass (>= 3.4.0, < 4.0)
		middleman-autoprefixer (2.7.1)
		  autoprefixer-rails (>= 6.5.2, < 7.0.0)
		  middleman-core (>= 3.3.3)
		middleman-cli (4.2.1)
		  thor (>= 0.17.0, < 2.0)
		middleman-core (4.2.1)
		  activesupport (>= 4.2, < 5.1)
		  addressable (~> 2.3)
		  backports (~> 3.6)
		  bundler (~> 1.1)
		  contracts (~> 0.13.0)
		  dotenv
		  erubis
		  execjs (~> 2.0)
		  fast_blank
		  fastimage (~> 2.0)
		  hamster (~> 3.0)
		  hashie (~> 3.4)
		  i18n (~> 0.7.0)
		  listen (~> 3.0.0)
		  memoist (~> 0.14)
		  padrino-helpers (~> 0.13.0)
		  parallel
		  rack (>= 1.4.5, < 3)
		  sass (>= 3.4)
		  servolux
		  tilt (~> 2.0)
		  uglifier (~> 3.0)
		middleman-livereload (3.4.6)
		  em-websocket (~> 0.5.1)
		  middleman-core (>= 3.3)
		  rack-livereload (~> 0.3.15)
		middleman-sprockets (4.1.0)
		  middleman-core (~> 4.0)
		  sprockets (>= 3.0)
		middleman-syntax (3.0.0)
		  middleman-core (>= 3.2)
		  rouge (~> 2.0)
		mini_racer (0.1.12)
		  libv8 (~> 5.9)
		minitest (5.10.3)
		padrino-helpers (0.13.3.4)
		  i18n (~> 0.6, >= 0.6.7)
		  padrino-support (= 0.13.3.4)
		  tilt (>= 1.4.1, < 3)
		padrino-support (0.13.3.4)
		  activesupport (>= 3.1)
		parallel (1.12.0)
		public_suffix (2.0.5)
		rack (2.0.3)
		rack-livereload (0.3.16)
		  rack
		rb-fsevent (0.10.2)
		rb-inotify (0.9.10)
		  ffi (>= 0.5.0, < 2)
		redcarpet (3.4.0)
		rouge (2.0.7)
		sass (3.4.25)
		servolux (0.13.0)
		sprockets (3.7.1)
		  concurrent-ruby (~> 1.0)
		  rack (> 1, < 3)
		temple (0.8.0)
		thor (0.19.4)
		thread_safe (0.3.6)
		tilt (2.0.8)
		tzinfo (1.2.3)
		  thread_safe (~> 0.1)
		uglifier (3.2.0)
		  execjs (>= 0.3.0, < 3)

	PLATFORMS
	  ruby

	DEPENDENCIES
	  middleman (~> 4.2.1)
	  middleman-autoprefixer (~> 2.7.0)
	  middleman-livereload (~> 3.4.3)
	  middleman-sprockets (~> 4.1.0)
	  middleman-syntax (~> 3.0.0)
	  mini_racer
	  redcarpet (~> 3.4.0)
	  rouge (~> 2.0.5)

	BUNDLED WITH
	   1.15.3

### Config.rb ###

	# Markdown
	set :markdown_engine, :redcarpet
	set :markdown,
		fenced_code_blocks: true,
		smartypants: true,
		disable_indented_code_blocks: true,
		prettify: true,
		tables: true,
		with_toc_data: true,
		no_intra_emphasis: true

	# Assets
	set :css_dir, 'stylesheets'
	set :js_dir, 'javascripts'
	set :images_dir, 'images'
	set :fonts_dir, 'fonts'

	# Activate the syntax highlighter
	activate :syntax
	ready do
	  require './lib/multilang.rb'
	end

	activate :sprockets

	activate :autoprefixer do |config|
	  config.browsers = ['last 2 version', 'Firefox ESR']
	  config.cascade  = false
	  config.inline   = true
	end

	# Github pages require relative links
	activate :relative_assets
	set :relative_links, true

	# Build Configuration
	configure :build do
	  # If you're having trouble with Middleman hanging, commenting
	  # out the following two lines has been known to help
	  activate :minify_css
	  activate :minify_javascript
	  # activate :relative_assets
	  # activate :asset_hash
	  # activate :gzip
	end

	# Deploy Configuration
	# If you want Middleman to listen on a different port, you can set that below

	# Activate Live Reload
	activate :livereload, host: '162.253.xxx.xxx'

### Gemfile ###

	source 'https://rubygems.org'

	gem 'middleman', '~> 4.2'
	gem 'middleman-autoprefixer', '~> 2.7'
	gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
	gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
	gem 'mini_racer'
	gem "middleman-livereload", "~> 3.4.3"

### Gemfile.lock ###

	GEM
	  remote: https://rubygems.org/
	  specs:
		activesupport (5.0.4)
		  concurrent-ruby (~> 1.0, >= 1.0.2)
		  i18n (~> 0.7)
		  minitest (~> 5.1)
		  tzinfo (~> 1.1)
		addressable (2.5.1)
		  public_suffix (~> 2.0, >= 2.0.2)
		autoprefixer-rails (7.1.2.3)
		  execjs
		backports (3.8.0)
		coffee-script (2.4.1)
		  coffee-script-source
		  execjs
		coffee-script-source (1.12.2)
		compass-import-once (1.0.5)
		  sass (>= 3.2, < 3.5)
		concurrent-ruby (1.0.5)
		contracts (0.13.0)
		dotenv (2.2.1)
		em-websocket (0.5.1)
		  eventmachine (>= 0.12.9)
		  http_parser.rb (~> 0.6.0)
		erubis (2.7.0)
		eventmachine (1.2.3)
		execjs (2.7.0)
		fast_blank (1.0.0)
		fastimage (2.1.0)
		ffi (1.9.18)
		haml (5.0.1)
		  temple (>= 0.8.0)
		  tilt
		hamster (3.0.0)
		  concurrent-ruby (~> 1.0)
		hashie (3.5.6)
		http_parser.rb (0.6.0)
		i18n (0.7.0)
		kramdown (1.14.0)
		libv8 (5.9.211.38.1-x86_64-linux)
		listen (3.0.8)
		  rb-fsevent (~> 0.9, >= 0.9.4)
		  rb-inotify (~> 0.9, >= 0.9.7)
		memoist (0.16.0)
		middleman (4.2.1)
		  coffee-script (~> 2.2)
		  compass-import-once (= 1.0.5)
		  haml (>= 4.0.5)
		  kramdown (~> 1.2)
		  middleman-cli (= 4.2.1)
		  middleman-core (= 4.2.1)
		  sass (>= 3.4.0, < 4.0)
		middleman-autoprefixer (2.8.0)
		  autoprefixer-rails (>= 7.0.1, < 8.0.0)
		  middleman-core (>= 3.3.3)
		middleman-cli (4.2.1)
		  thor (>= 0.17.0, < 2.0)
		middleman-core (4.2.1)
		  activesupport (>= 4.2, < 5.1)
		  addressable (~> 2.3)
		  backports (~> 3.6)
		  bundler (~> 1.1)
		  contracts (~> 0.13.0)
		  dotenv
		  erubis
		  execjs (~> 2.0)
		  fast_blank
		  fastimage (~> 2.0)
		  hamster (~> 3.0)
		  hashie (~> 3.4)
		  i18n (~> 0.7.0)
		  listen (~> 3.0.0)
		  memoist (~> 0.14)
		  padrino-helpers (~> 0.13.0)
		  parallel
		  rack (>= 1.4.5, < 3)
		  sass (>= 3.4)
		  servolux
		  tilt (~> 2.0)
		  uglifier (~> 3.0)
		middleman-livereload (3.4.6)
		  em-websocket (~> 0.5.1)
		  middleman-core (>= 3.3)
		  rack-livereload (~> 0.3.15)
		mini_racer (0.1.12)
		  libv8 (~> 5.9)
		minitest (5.10.3)
		padrino-helpers (0.13.3.4)
		  i18n (~> 0.6, >= 0.6.7)
		  padrino-support (= 0.13.3.4)
		  tilt (>= 1.4.1, < 3)
		padrino-support (0.13.3.4)
		  activesupport (>= 3.1)
		parallel (1.12.0)
		public_suffix (2.0.5)
		rack (2.0.3)
		rack-livereload (0.3.16)
		  rack
		rb-fsevent (0.10.2)
		rb-inotify (0.9.10)
		  ffi (>= 0.5.0, < 2)
		sass (3.4.25)
		servolux (0.13.0)
		temple (0.8.0)
		thor (0.19.4)
		thread_safe (0.3.6)
		tilt (2.0.8)
		tzinfo (1.2.3)
		  thread_safe (~> 0.1)
		uglifier (3.2.0)
		  execjs (>= 0.3.0, < 3)

	PLATFORMS
	  ruby

	DEPENDENCIES
	  middleman (~> 4.2)
	  middleman-autoprefixer (~> 2.7)
	  middleman-livereload (~> 3.4.3)
	  mini_racer
	  tzinfo-data
	  wdm (~> 0.1)

	BUNDLED WITH
	   1.15.3

### Config.rb ###

	# Activate and configure extensions
	# https://middlemanapp.com/advanced/configuration/#configuring-extensions

	activate :autoprefixer do |prefix|
	  prefix.browsers = "last 2 versions"
	end

	# Layouts
	# https://middlemanapp.com/basics/layouts/

	# Per-page layout changes
	page '/*.xml', layout: false
	page '/*.json', layout: false
	page '/*.txt', layout: false

	# With alternative layout
	# page '/path/to/file.html', layout: 'other_layout'

	# Proxy pages
	# https://middlemanapp.com/advanced/dynamic-pages/

	# proxy(
	#   '/this-page-has-no-template.html',
	#   '/template-file.html',
	#   locals: {
	#     which_fake_page: 'Rendering a fake page with a local variable'
	#   },
	# )

	# Helpers
	# Methods defined in the helpers block are available in templates
	# https://middlemanapp.com/basics/helper-methods/

	# helpers do
	#   def some_helper
	#     'Helping'
	#   end
	# end

	# Build-specific configuration
	# https://middlemanapp.com/advanced/configuration/#environment-specific-settings

	# configure :build do
	#   activate :minify_css
	#   activate :minify_javascript
	# end

	set :bind_address, '162.253.xxx.xxx'

	activate :livereload, host: '162.253.xxx.xxx'

**Comment by sandstrom** [comment]
@little-apps Thanks for taking time submitting the issue!

Can you explain when/why you want to run in daemon-mode?

I'm happy to review a PR if you manage to track down the bug/issue!

*This repo is maintained by a few people contributing some of their spare time, so without a patch/pr to fix the issue it's unlikely it'll go anywhere.*

**Comment by little-apps** [comment]
I opened [an issue with EventMachine](https://github.com/eventmachine/eventmachine/issues/796) as there are workarounds to this problem but the fix ultimately lies with EventMachine. In the meantime, I'd say the best workaround is to run middleman background from the command line, like so:

 > bundle exec middleman 2>&1 > /dev/null &

**Comment by sandstrom** [comment]
@little-apps Sounds good! Can we close this PR then?
